### ISSUE TITLE
Use appveyor for running windows tests

### ISSUE THREAD

**Issue by parkouss** [parkouss/funq#10]
It would be awesome to have appveyor run some tests on windows, with Qt4 and possibly Qt5 on the code base.

The tested applications must be compiled with libFunq, as for now windows DLL injection is not working well.

**Comment by ubruhin** [comment]
AppVeyor was added in #32, although some tests are still disabled. And I forgot do add a badge to the readme :(

**Comment by rafaeldelucena** [comment]
@ubruhin Can you do that in a new PR? =P

**Comment by rafaeldelucena** [comment]
Closed by https://github.com/parkouss/funq/pull/36
