### ISSUE TITLE
Error 299 - Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

### ISSUE THREAD

**Issue by diwakar09** [parkouss/funq#21]
I am trying to use Funq on Win7_64, using python 2.7, QT 5.1 64bit
Installation went fine.
However when trying to use it, I ran into problems,

\Python27\Scripts\funq.exe --pick release\player_tester.exe
Traceback (most recent call last):
  File "C:\Python27\Scripts\funq-script.py", line 9, in <module>
    load_entry_point('funq-server==1.1.4', 'console_scripts', 'funq')()
  File "C:\Python27\lib\site-packages\funq_server\runner.py", line 114, in main
    sys.exit(runner.run())
  File "C:\Python27\lib\site-packages\funq_server\runner.py", line 109, in run
    return injector.run()
  File "C:\Python27\lib\site-packages\funq_server\runner.py", line 52, in run
    self.start_subprocess()
  File "C:\Python27\lib\site-packages\funq_server\runner_win.py", line 60, in start_subprocess
    proc.scan_modules()
  File "C:\Python27\lib\site-packages\winappdbg\module.py", line 1056, in scan_modules
    dwProcessId) as hSnapshot:
  File "C:\Python27\lib\site-packages\winappdbg\win32\kernel32.py", line 4208, in CreateToolhelp32Snapshot
    raise ctypes.WinError()
WindowsError: [Error 299] Only part of a ReadProcessMemory or WriteProcessMemory request was completed.

Appreciate any help or pointers.

Thanks,
Diwakar

**Comment by parkouss** [comment]
Unfortunately windows support is not really good. Note that funq use winappdbg to try to inject the funq's server code inside the running executable: https://github.com/parkouss/funq/blob/master/server/funq_server/runner_win.py#L60
Unfortunately this seems to fail, at least on your platform; I don't currently have time to try to make it work though - feel free to have a look if you do!

**Comment by parkouss** [comment]
Still, you can build the application with funq : http://funq.readthedocs.io/en/latest/libFunq.html. This will bypass the error, since the funq code won't need to be injeted any more.

**Comment by diwakar09** [comment]
It was some timing issue,
I added some delay before https://github.com/parkouss/funq/blob/master/server/funq_server/runner_win.py#L46 

Now, atleast it is not failing for the same. :)
It seems TCP server is not starting.

Thanks,
Diwakar

**Comment by ubruhin** [comment]
This was actually fixed (or let's call it "worked around" :wink:) in #32, so I think this issue can be closed :)

**Comment by rafaeldelucena** [comment]
Closed by #32
