### ISSUE TITLE
[Question] It's possible to run the client on a remote machine?

### ISSUE THREAD

**Issue by rafaeldelucena** [parkouss/funq#22]
I'm looking at the server code and I found this line https://github.com/parkouss/funq/blob/master/server/libFunq/funq.cpp#L69, which makes the server host hardcoded to local address.

**Comment by parkouss** [comment]
It should be possible, please look at the documentation about detached in there:
http://funq.readthedocs.io/en/latest/funq_conf.html#the-funq-conf-configuration-file

The executable option must specify the remote adress, starting with socket:// - and on the remote server, the application have to be started using the funq wrapper, or compiled with libFunc.

**Comment by rafaeldelucena** [comment]
It's only work in a the same machine, I wrote a patch enabling the user setting a custom host on funq_server at https://github.com/parkouss/funq/pull/25
