### ISSUE TITLE
Funq with target device

### ISSUE THREAD

**Issue by spadilam** [parkouss/funq#28]
Can I use the funq server to connect with target device and still automate my clicks and other functionalities on the target device from my PC.

Regards,
Srinivas Padilam.

**Comment by rafaeldelucena** [comment]
Hello,

You will run the funq-server on the target device like:

```
funq --host 0.0.0.0 --port 9999 your_application
```

And in your PC you can connect with the code snippet bellow:

```
from funq.client import FunqClient

# Put your targer device ip here
funq = FunqClient('192.168.0.10', 9999)
...
```

**Comment by rafaeldelucena** [comment]
@spadilam any news about this question? it's resolved?
