### ISSUE TITLE
Version 1.14 is missing

### ISSUE THREAD

**Issue by rafaeldelucena** [parkouss/funq#52]
I do not found the tag for this release, @parkouss do you have a copy in a local repository?

Thanks

**Comment by rafaeldelucena** [comment]
Also some new features are already merged, they will be part of 1.14 too or we must create a new one?

**Comment by parkouss** [comment]
Argh. I guess this is a mistake on my side...
Yeah it would be nice to create a new version, 1.1.5 for example - and with a tag :).

Do you need/want some help for that?

**Comment by rafaeldelucena** [comment]
Ok, I can do that =)

Also if you don't have the 1.14 in a local branch I can match the code from pip and create a tag for 1.14 just for historical reasons =P

**Comment by rafaeldelucena** [comment]
Lurking into git log history i found this:

> commit ca6215a24fb8c21e8018c23f4686ecfcaf3d6318
Author: Julien Pagès <j.parkouss@gmail.com>
Date:   Wed Apr 22 15:26:44 2015 +0200
    bump version to 1.1.4 (bad pypi manipulation)


Can I use that commit to generate a tag for 1.1.4?

**Comment by rafaeldelucena** [comment]
Hi have created the new tag, could you update the pypi package?
