### ISSUE TITLE
Add proper Python 3 compatibility

### ISSUE THREAD

**Issue by ubruhin** [parkouss/funq#58]
Currently the client has set `use_2to3 = True` in its `setup.py` to get compatibility with Python 3. But unfortunately this automatic conversion doesn't work always properly and is very annoying to debug as the code of an installed package is not the same as the original code of the repository. In #57 I already needed to implement a hacky workaround to prevent 2to3 from performing an illegal conversion.

It would be nice to remove `use_2to3 = True` from `setup.py` and properly implement Python 3 compatibility in all files. Of course while still keeping Python 2 compatibility, as Funq only works with Python 2 on Windows.

**Comment by dbrgn** [comment]
> as Funq only works with Python 2 on Windows

winappdbg seems pretty much dead (last release in 2013). Maybe there's a package that could replace it?

**Comment by dbrgn** [comment]
Oh, wait, there's some activity here apparently! https://github.com/MarioVilas/winappdbg
